# This is a basic workflow that is manually triggered for deploying changes to production

name: Manual Deploy workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy to production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    # - uses: actions/checkout@v2
    # - run: |
    #       git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git rm yarn.lock 
    - run: npm i
    - run: npm test
    - run: npm run build --if-present

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
        heroku_app_name: radiant-journey-43861
        heroku_email: tarunbhartiya7@gmail.com
        procfile: "web: npm start"
    
    # - name: Deploy to Heroku
    #   env: 
    #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    #   if: github.ref == 'refs/heads/master' && job.status == 'success'
    #   run: |
    #     git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/radiant-journey-43861.git
    #     git push heroku HEAD:master -f
